CREATE TABLE USER_ROLE(
	role_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,--0 for base emp, 1 for management
	name VARCHAR(25)
)

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REIMB_TYPE VARCHAR(10)
)

--INSERT TABLE ERS_REIMBURSEMENT_TYPE RENAME COLUMN REIM_TYPE_ID TO REIMB_TYPE_ID;
INSERT INTO ers_reimbursement_type (REIMB_TYPE) VALUES
	('FOOD');

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REIMB_STATUS VARCHAR(10)
)

CREATE TABLE APP_USER (
	-- columns to be defined in this table
	-- column_name column_type CONSTRAINTS,	
--	id SERIAL PRIMARY KEY, -- Very common mechanism for auto incrementing
	user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- newer mechanism
	--VARCHAR2 doesnt discriminate against null or unique strings
	username VARCHAR(50) UNIQUE,
	password VARCHAR(50),
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	role_id INTEGER,
	FOREIGN key (role_id)  REFERENCES USER_ROLE (role_id)
);

CREATE TABLE ERS_REIMBURSMENT(
	REIMB_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,--*
	REIMB_AMOUNT INTEGER,--*
	REIMB_SUBMITTED TIMESTAMP,--*
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_RECEIPT BYTEA,--replacement for BLOB:https://dba.stackexchange.com/questions/125831/migrating-blob-in-oracle-into-postgresql
	REIMB_AUTHOR INTEGER,
	FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS (ERS_USER_ID),--*user that submits it
	REIMB_RESOLVER INTEGER,
	FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS (ERS_USER_ID),--user that accepts/rejects the claim
	REIMB_STATUS_ID INTEGER,
	FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID),--*
	REIMB_TYPE_ID INTEGER,
	FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID)--*
)

